#pragma checksum "..\..\..\RemoteControlGui.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "AD6C42B5EF4D2FDC481066BEA8CDEBF16A12F138BF99BB47E38CA78F5EBBB72D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RemoteControl;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RemoteControl {
    
    
    /// <summary>
    /// RemoteControlGui
    /// </summary>
    public partial class RemoteControlGui : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 39 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Root;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NewBotAddress;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NewBotLabel;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox BotListBox;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox SyncAllCheckbox;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\RemoteControlGui.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel BotPanelsContainer;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RemoteControl;component/remotecontrolgui.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\RemoteControlGui.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.NewBotAddress = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.NewBotLabel = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            
            #line 67 "..\..\..\RemoteControlGui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddBot_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 68 "..\..\..\RemoteControlGui.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RemoveBot_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BotListBox = ((System.Windows.Controls.ListBox)(target));
            return;
            case 7:
            this.SyncAllCheckbox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 84 "..\..\..\RemoteControlGui.xaml"
            this.SyncAllCheckbox.Checked += new System.Windows.RoutedEventHandler(this.SyncAllCheckbox_Changed);
            
            #line default
            #line hidden
            
            #line 84 "..\..\..\RemoteControlGui.xaml"
            this.SyncAllCheckbox.Unchecked += new System.Windows.RoutedEventHandler(this.SyncAllCheckbox_Changed);
            
            #line default
            #line hidden
            return;
            case 8:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.BotPanelsContainer = ((System.Windows.Controls.WrapPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

